package org.brjia.qs.model;

import java.util.Date;

public class AreaRegDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_reg.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_reg.name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_reg.create_user
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_reg.create_time
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_reg.office
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String office;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_reg.id
     *
     * @return the value of area_reg.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_reg.id
     *
     * @param id the value for area_reg.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_reg.name
     *
     * @return the value of area_reg.name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_reg.name
     *
     * @param name the value for area_reg.name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_reg.create_user
     *
     * @return the value of area_reg.create_user
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_reg.create_user
     *
     * @param createUser the value for area_reg.create_user
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_reg.create_time
     *
     * @return the value of area_reg.create_time
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_reg.create_time
     *
     * @param createTime the value for area_reg.create_time
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_reg.office
     *
     * @return the value of area_reg.office
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getOffice() {
        return office;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_reg.office
     *
     * @param office the value for area_reg.office
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setOffice(String office) {
        this.office = office == null ? null : office.trim();
    }
}