package org.brjia.qs.model;

public class FightingListDataRegDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.year
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.area_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.summary_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer summaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.member_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.kill_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer killQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.assist_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer assistQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.carry_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer carryQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.output_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer outputM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.cure_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer cureM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.bear_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer bearM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.corpse_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer corpseQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.relive_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer reliveQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.killed_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer killedQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.tank_kill_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer tankKillQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.hero
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String hero;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.driver
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String driver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.member_name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.level
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.id
     *
     * @return the value of activity_data.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.id
     *
     * @param id the value for activity_data.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.year
     *
     * @return the value of activity_data.year
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.year
     *
     * @param year the value for activity_data.year
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.area_id
     *
     * @return the value of activity_data.area_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.area_id
     *
     * @param areaId the value for activity_data.area_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.summary_id
     *
     * @return the value of activity_data.summary_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getSummaryId() {
        return summaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.summary_id
     *
     * @param summaryId the value for activity_data.summary_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setSummaryId(Integer summaryId) {
        this.summaryId = summaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.member_id
     *
     * @return the value of activity_data.member_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.member_id
     *
     * @param memberId the value for activity_data.member_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.kill_q
     *
     * @return the value of activity_data.kill_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getKillQ() {
        return killQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.kill_q
     *
     * @param killQ the value for activity_data.kill_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setKillQ(Integer killQ) {
        this.killQ = killQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.assist_q
     *
     * @return the value of activity_data.assist_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getAssistQ() {
        return assistQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.assist_q
     *
     * @param assistQ the value for activity_data.assist_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setAssistQ(Integer assistQ) {
        this.assistQ = assistQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.carry_q
     *
     * @return the value of activity_data.carry_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getCarryQ() {
        return carryQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.carry_q
     *
     * @param carryQ the value for activity_data.carry_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setCarryQ(Integer carryQ) {
        this.carryQ = carryQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.output_m
     *
     * @return the value of activity_data.output_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getOutputM() {
        return outputM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.output_m
     *
     * @param outputM the value for activity_data.output_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setOutputM(Integer outputM) {
        this.outputM = outputM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.cure_m
     *
     * @return the value of activity_data.cure_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getCureM() {
        return cureM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.cure_m
     *
     * @param cureM the value for activity_data.cure_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setCureM(Integer cureM) {
        this.cureM = cureM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.bear_m
     *
     * @return the value of activity_data.bear_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getBearM() {
        return bearM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.bear_m
     *
     * @param bearM the value for activity_data.bear_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setBearM(Integer bearM) {
        this.bearM = bearM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.corpse_q
     *
     * @return the value of activity_data.corpse_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getCorpseQ() {
        return corpseQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.corpse_q
     *
     * @param corpseQ the value for activity_data.corpse_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setCorpseQ(Integer corpseQ) {
        this.corpseQ = corpseQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.relive_q
     *
     * @return the value of activity_data.relive_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getReliveQ() {
        return reliveQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.relive_q
     *
     * @param reliveQ the value for activity_data.relive_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setReliveQ(Integer reliveQ) {
        this.reliveQ = reliveQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.killed_q
     *
     * @return the value of activity_data.killed_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getKilledQ() {
        return killedQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.killed_q
     *
     * @param killedQ the value for activity_data.killed_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setKilledQ(Integer killedQ) {
        this.killedQ = killedQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.tank_kill_q
     *
     * @return the value of activity_data.tank_kill_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getTankKillQ() {
        return tankKillQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.tank_kill_q
     *
     * @param tankKillQ the value for activity_data.tank_kill_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setTankKillQ(Integer tankKillQ) {
        this.tankKillQ = tankKillQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.hero
     *
     * @return the value of activity_data.hero
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getHero() {
        return hero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.hero
     *
     * @param hero the value for activity_data.hero
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setHero(String hero) {
        this.hero = hero == null ? null : hero.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.driver
     *
     * @return the value of activity_data.driver
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getDriver() {
        return driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.driver
     *
     * @param driver the value for activity_data.driver
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setDriver(String driver) {
        this.driver = driver == null ? null : driver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.member_name
     *
     * @return the value of activity_data.member_name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.member_name
     *
     * @param memberName the value for activity_data.member_name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.level
     *
     * @return the value of activity_data.level
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.level
     *
     * @param level the value for activity_data.level
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }
}