package org.brjia.qs.model;

import java.util.ArrayList;
import java.util.List;

public class FightingListDataRegDTOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public FightingListDataRegDTOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(Integer value) {
            addCriterion("year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(Integer value) {
            addCriterion("year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(Integer value) {
            addCriterion("year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(Integer value) {
            addCriterion("year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(Integer value) {
            addCriterion("year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<Integer> values) {
            addCriterion("year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<Integer> values) {
            addCriterion("year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(Integer value1, Integer value2) {
            addCriterion("year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(Integer value1, Integer value2) {
            addCriterion("year not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("area_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("area_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(Integer value) {
            addCriterion("area_id =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(Integer value) {
            addCriterion("area_id <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(Integer value) {
            addCriterion("area_id >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("area_id >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(Integer value) {
            addCriterion("area_id <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(Integer value) {
            addCriterion("area_id <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<Integer> values) {
            addCriterion("area_id in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<Integer> values) {
            addCriterion("area_id not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(Integer value1, Integer value2) {
            addCriterion("area_id between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("area_id not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdIsNull() {
            addCriterion("summary_id is null");
            return (Criteria) this;
        }

        public Criteria andSummaryIdIsNotNull() {
            addCriterion("summary_id is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryIdEqualTo(Integer value) {
            addCriterion("summary_id =", value, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdNotEqualTo(Integer value) {
            addCriterion("summary_id <>", value, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdGreaterThan(Integer value) {
            addCriterion("summary_id >", value, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("summary_id >=", value, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdLessThan(Integer value) {
            addCriterion("summary_id <", value, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdLessThanOrEqualTo(Integer value) {
            addCriterion("summary_id <=", value, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdIn(List<Integer> values) {
            addCriterion("summary_id in", values, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdNotIn(List<Integer> values) {
            addCriterion("summary_id not in", values, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdBetween(Integer value1, Integer value2) {
            addCriterion("summary_id between", value1, value2, "summaryId");
            return (Criteria) this;
        }

        public Criteria andSummaryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("summary_id not between", value1, value2, "summaryId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("member_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("member_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(Integer value) {
            addCriterion("member_id =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(Integer value) {
            addCriterion("member_id <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(Integer value) {
            addCriterion("member_id >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("member_id >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(Integer value) {
            addCriterion("member_id <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(Integer value) {
            addCriterion("member_id <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<Integer> values) {
            addCriterion("member_id in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<Integer> values) {
            addCriterion("member_id not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(Integer value1, Integer value2) {
            addCriterion("member_id between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(Integer value1, Integer value2) {
            addCriterion("member_id not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andKillQIsNull() {
            addCriterion("kill_q is null");
            return (Criteria) this;
        }

        public Criteria andKillQIsNotNull() {
            addCriterion("kill_q is not null");
            return (Criteria) this;
        }

        public Criteria andKillQEqualTo(Integer value) {
            addCriterion("kill_q =", value, "killQ");
            return (Criteria) this;
        }

        public Criteria andKillQNotEqualTo(Integer value) {
            addCriterion("kill_q <>", value, "killQ");
            return (Criteria) this;
        }

        public Criteria andKillQGreaterThan(Integer value) {
            addCriterion("kill_q >", value, "killQ");
            return (Criteria) this;
        }

        public Criteria andKillQGreaterThanOrEqualTo(Integer value) {
            addCriterion("kill_q >=", value, "killQ");
            return (Criteria) this;
        }

        public Criteria andKillQLessThan(Integer value) {
            addCriterion("kill_q <", value, "killQ");
            return (Criteria) this;
        }

        public Criteria andKillQLessThanOrEqualTo(Integer value) {
            addCriterion("kill_q <=", value, "killQ");
            return (Criteria) this;
        }

        public Criteria andKillQIn(List<Integer> values) {
            addCriterion("kill_q in", values, "killQ");
            return (Criteria) this;
        }

        public Criteria andKillQNotIn(List<Integer> values) {
            addCriterion("kill_q not in", values, "killQ");
            return (Criteria) this;
        }

        public Criteria andKillQBetween(Integer value1, Integer value2) {
            addCriterion("kill_q between", value1, value2, "killQ");
            return (Criteria) this;
        }

        public Criteria andKillQNotBetween(Integer value1, Integer value2) {
            addCriterion("kill_q not between", value1, value2, "killQ");
            return (Criteria) this;
        }

        public Criteria andAssistQIsNull() {
            addCriterion("assist_q is null");
            return (Criteria) this;
        }

        public Criteria andAssistQIsNotNull() {
            addCriterion("assist_q is not null");
            return (Criteria) this;
        }

        public Criteria andAssistQEqualTo(Integer value) {
            addCriterion("assist_q =", value, "assistQ");
            return (Criteria) this;
        }

        public Criteria andAssistQNotEqualTo(Integer value) {
            addCriterion("assist_q <>", value, "assistQ");
            return (Criteria) this;
        }

        public Criteria andAssistQGreaterThan(Integer value) {
            addCriterion("assist_q >", value, "assistQ");
            return (Criteria) this;
        }

        public Criteria andAssistQGreaterThanOrEqualTo(Integer value) {
            addCriterion("assist_q >=", value, "assistQ");
            return (Criteria) this;
        }

        public Criteria andAssistQLessThan(Integer value) {
            addCriterion("assist_q <", value, "assistQ");
            return (Criteria) this;
        }

        public Criteria andAssistQLessThanOrEqualTo(Integer value) {
            addCriterion("assist_q <=", value, "assistQ");
            return (Criteria) this;
        }

        public Criteria andAssistQIn(List<Integer> values) {
            addCriterion("assist_q in", values, "assistQ");
            return (Criteria) this;
        }

        public Criteria andAssistQNotIn(List<Integer> values) {
            addCriterion("assist_q not in", values, "assistQ");
            return (Criteria) this;
        }

        public Criteria andAssistQBetween(Integer value1, Integer value2) {
            addCriterion("assist_q between", value1, value2, "assistQ");
            return (Criteria) this;
        }

        public Criteria andAssistQNotBetween(Integer value1, Integer value2) {
            addCriterion("assist_q not between", value1, value2, "assistQ");
            return (Criteria) this;
        }

        public Criteria andCarryQIsNull() {
            addCriterion("carry_q is null");
            return (Criteria) this;
        }

        public Criteria andCarryQIsNotNull() {
            addCriterion("carry_q is not null");
            return (Criteria) this;
        }

        public Criteria andCarryQEqualTo(Integer value) {
            addCriterion("carry_q =", value, "carryQ");
            return (Criteria) this;
        }

        public Criteria andCarryQNotEqualTo(Integer value) {
            addCriterion("carry_q <>", value, "carryQ");
            return (Criteria) this;
        }

        public Criteria andCarryQGreaterThan(Integer value) {
            addCriterion("carry_q >", value, "carryQ");
            return (Criteria) this;
        }

        public Criteria andCarryQGreaterThanOrEqualTo(Integer value) {
            addCriterion("carry_q >=", value, "carryQ");
            return (Criteria) this;
        }

        public Criteria andCarryQLessThan(Integer value) {
            addCriterion("carry_q <", value, "carryQ");
            return (Criteria) this;
        }

        public Criteria andCarryQLessThanOrEqualTo(Integer value) {
            addCriterion("carry_q <=", value, "carryQ");
            return (Criteria) this;
        }

        public Criteria andCarryQIn(List<Integer> values) {
            addCriterion("carry_q in", values, "carryQ");
            return (Criteria) this;
        }

        public Criteria andCarryQNotIn(List<Integer> values) {
            addCriterion("carry_q not in", values, "carryQ");
            return (Criteria) this;
        }

        public Criteria andCarryQBetween(Integer value1, Integer value2) {
            addCriterion("carry_q between", value1, value2, "carryQ");
            return (Criteria) this;
        }

        public Criteria andCarryQNotBetween(Integer value1, Integer value2) {
            addCriterion("carry_q not between", value1, value2, "carryQ");
            return (Criteria) this;
        }

        public Criteria andOutputMIsNull() {
            addCriterion("output_m is null");
            return (Criteria) this;
        }

        public Criteria andOutputMIsNotNull() {
            addCriterion("output_m is not null");
            return (Criteria) this;
        }

        public Criteria andOutputMEqualTo(Integer value) {
            addCriterion("output_m =", value, "outputM");
            return (Criteria) this;
        }

        public Criteria andOutputMNotEqualTo(Integer value) {
            addCriterion("output_m <>", value, "outputM");
            return (Criteria) this;
        }

        public Criteria andOutputMGreaterThan(Integer value) {
            addCriterion("output_m >", value, "outputM");
            return (Criteria) this;
        }

        public Criteria andOutputMGreaterThanOrEqualTo(Integer value) {
            addCriterion("output_m >=", value, "outputM");
            return (Criteria) this;
        }

        public Criteria andOutputMLessThan(Integer value) {
            addCriterion("output_m <", value, "outputM");
            return (Criteria) this;
        }

        public Criteria andOutputMLessThanOrEqualTo(Integer value) {
            addCriterion("output_m <=", value, "outputM");
            return (Criteria) this;
        }

        public Criteria andOutputMIn(List<Integer> values) {
            addCriterion("output_m in", values, "outputM");
            return (Criteria) this;
        }

        public Criteria andOutputMNotIn(List<Integer> values) {
            addCriterion("output_m not in", values, "outputM");
            return (Criteria) this;
        }

        public Criteria andOutputMBetween(Integer value1, Integer value2) {
            addCriterion("output_m between", value1, value2, "outputM");
            return (Criteria) this;
        }

        public Criteria andOutputMNotBetween(Integer value1, Integer value2) {
            addCriterion("output_m not between", value1, value2, "outputM");
            return (Criteria) this;
        }

        public Criteria andCureMIsNull() {
            addCriterion("cure_m is null");
            return (Criteria) this;
        }

        public Criteria andCureMIsNotNull() {
            addCriterion("cure_m is not null");
            return (Criteria) this;
        }

        public Criteria andCureMEqualTo(Integer value) {
            addCriterion("cure_m =", value, "cureM");
            return (Criteria) this;
        }

        public Criteria andCureMNotEqualTo(Integer value) {
            addCriterion("cure_m <>", value, "cureM");
            return (Criteria) this;
        }

        public Criteria andCureMGreaterThan(Integer value) {
            addCriterion("cure_m >", value, "cureM");
            return (Criteria) this;
        }

        public Criteria andCureMGreaterThanOrEqualTo(Integer value) {
            addCriterion("cure_m >=", value, "cureM");
            return (Criteria) this;
        }

        public Criteria andCureMLessThan(Integer value) {
            addCriterion("cure_m <", value, "cureM");
            return (Criteria) this;
        }

        public Criteria andCureMLessThanOrEqualTo(Integer value) {
            addCriterion("cure_m <=", value, "cureM");
            return (Criteria) this;
        }

        public Criteria andCureMIn(List<Integer> values) {
            addCriterion("cure_m in", values, "cureM");
            return (Criteria) this;
        }

        public Criteria andCureMNotIn(List<Integer> values) {
            addCriterion("cure_m not in", values, "cureM");
            return (Criteria) this;
        }

        public Criteria andCureMBetween(Integer value1, Integer value2) {
            addCriterion("cure_m between", value1, value2, "cureM");
            return (Criteria) this;
        }

        public Criteria andCureMNotBetween(Integer value1, Integer value2) {
            addCriterion("cure_m not between", value1, value2, "cureM");
            return (Criteria) this;
        }

        public Criteria andBearMIsNull() {
            addCriterion("bear_m is null");
            return (Criteria) this;
        }

        public Criteria andBearMIsNotNull() {
            addCriterion("bear_m is not null");
            return (Criteria) this;
        }

        public Criteria andBearMEqualTo(Integer value) {
            addCriterion("bear_m =", value, "bearM");
            return (Criteria) this;
        }

        public Criteria andBearMNotEqualTo(Integer value) {
            addCriterion("bear_m <>", value, "bearM");
            return (Criteria) this;
        }

        public Criteria andBearMGreaterThan(Integer value) {
            addCriterion("bear_m >", value, "bearM");
            return (Criteria) this;
        }

        public Criteria andBearMGreaterThanOrEqualTo(Integer value) {
            addCriterion("bear_m >=", value, "bearM");
            return (Criteria) this;
        }

        public Criteria andBearMLessThan(Integer value) {
            addCriterion("bear_m <", value, "bearM");
            return (Criteria) this;
        }

        public Criteria andBearMLessThanOrEqualTo(Integer value) {
            addCriterion("bear_m <=", value, "bearM");
            return (Criteria) this;
        }

        public Criteria andBearMIn(List<Integer> values) {
            addCriterion("bear_m in", values, "bearM");
            return (Criteria) this;
        }

        public Criteria andBearMNotIn(List<Integer> values) {
            addCriterion("bear_m not in", values, "bearM");
            return (Criteria) this;
        }

        public Criteria andBearMBetween(Integer value1, Integer value2) {
            addCriterion("bear_m between", value1, value2, "bearM");
            return (Criteria) this;
        }

        public Criteria andBearMNotBetween(Integer value1, Integer value2) {
            addCriterion("bear_m not between", value1, value2, "bearM");
            return (Criteria) this;
        }

        public Criteria andCorpseQIsNull() {
            addCriterion("corpse_q is null");
            return (Criteria) this;
        }

        public Criteria andCorpseQIsNotNull() {
            addCriterion("corpse_q is not null");
            return (Criteria) this;
        }

        public Criteria andCorpseQEqualTo(Integer value) {
            addCriterion("corpse_q =", value, "corpseQ");
            return (Criteria) this;
        }

        public Criteria andCorpseQNotEqualTo(Integer value) {
            addCriterion("corpse_q <>", value, "corpseQ");
            return (Criteria) this;
        }

        public Criteria andCorpseQGreaterThan(Integer value) {
            addCriterion("corpse_q >", value, "corpseQ");
            return (Criteria) this;
        }

        public Criteria andCorpseQGreaterThanOrEqualTo(Integer value) {
            addCriterion("corpse_q >=", value, "corpseQ");
            return (Criteria) this;
        }

        public Criteria andCorpseQLessThan(Integer value) {
            addCriterion("corpse_q <", value, "corpseQ");
            return (Criteria) this;
        }

        public Criteria andCorpseQLessThanOrEqualTo(Integer value) {
            addCriterion("corpse_q <=", value, "corpseQ");
            return (Criteria) this;
        }

        public Criteria andCorpseQIn(List<Integer> values) {
            addCriterion("corpse_q in", values, "corpseQ");
            return (Criteria) this;
        }

        public Criteria andCorpseQNotIn(List<Integer> values) {
            addCriterion("corpse_q not in", values, "corpseQ");
            return (Criteria) this;
        }

        public Criteria andCorpseQBetween(Integer value1, Integer value2) {
            addCriterion("corpse_q between", value1, value2, "corpseQ");
            return (Criteria) this;
        }

        public Criteria andCorpseQNotBetween(Integer value1, Integer value2) {
            addCriterion("corpse_q not between", value1, value2, "corpseQ");
            return (Criteria) this;
        }

        public Criteria andReliveQIsNull() {
            addCriterion("relive_q is null");
            return (Criteria) this;
        }

        public Criteria andReliveQIsNotNull() {
            addCriterion("relive_q is not null");
            return (Criteria) this;
        }

        public Criteria andReliveQEqualTo(Integer value) {
            addCriterion("relive_q =", value, "reliveQ");
            return (Criteria) this;
        }

        public Criteria andReliveQNotEqualTo(Integer value) {
            addCriterion("relive_q <>", value, "reliveQ");
            return (Criteria) this;
        }

        public Criteria andReliveQGreaterThan(Integer value) {
            addCriterion("relive_q >", value, "reliveQ");
            return (Criteria) this;
        }

        public Criteria andReliveQGreaterThanOrEqualTo(Integer value) {
            addCriterion("relive_q >=", value, "reliveQ");
            return (Criteria) this;
        }

        public Criteria andReliveQLessThan(Integer value) {
            addCriterion("relive_q <", value, "reliveQ");
            return (Criteria) this;
        }

        public Criteria andReliveQLessThanOrEqualTo(Integer value) {
            addCriterion("relive_q <=", value, "reliveQ");
            return (Criteria) this;
        }

        public Criteria andReliveQIn(List<Integer> values) {
            addCriterion("relive_q in", values, "reliveQ");
            return (Criteria) this;
        }

        public Criteria andReliveQNotIn(List<Integer> values) {
            addCriterion("relive_q not in", values, "reliveQ");
            return (Criteria) this;
        }

        public Criteria andReliveQBetween(Integer value1, Integer value2) {
            addCriterion("relive_q between", value1, value2, "reliveQ");
            return (Criteria) this;
        }

        public Criteria andReliveQNotBetween(Integer value1, Integer value2) {
            addCriterion("relive_q not between", value1, value2, "reliveQ");
            return (Criteria) this;
        }

        public Criteria andKilledQIsNull() {
            addCriterion("killed_q is null");
            return (Criteria) this;
        }

        public Criteria andKilledQIsNotNull() {
            addCriterion("killed_q is not null");
            return (Criteria) this;
        }

        public Criteria andKilledQEqualTo(Integer value) {
            addCriterion("killed_q =", value, "killedQ");
            return (Criteria) this;
        }

        public Criteria andKilledQNotEqualTo(Integer value) {
            addCriterion("killed_q <>", value, "killedQ");
            return (Criteria) this;
        }

        public Criteria andKilledQGreaterThan(Integer value) {
            addCriterion("killed_q >", value, "killedQ");
            return (Criteria) this;
        }

        public Criteria andKilledQGreaterThanOrEqualTo(Integer value) {
            addCriterion("killed_q >=", value, "killedQ");
            return (Criteria) this;
        }

        public Criteria andKilledQLessThan(Integer value) {
            addCriterion("killed_q <", value, "killedQ");
            return (Criteria) this;
        }

        public Criteria andKilledQLessThanOrEqualTo(Integer value) {
            addCriterion("killed_q <=", value, "killedQ");
            return (Criteria) this;
        }

        public Criteria andKilledQIn(List<Integer> values) {
            addCriterion("killed_q in", values, "killedQ");
            return (Criteria) this;
        }

        public Criteria andKilledQNotIn(List<Integer> values) {
            addCriterion("killed_q not in", values, "killedQ");
            return (Criteria) this;
        }

        public Criteria andKilledQBetween(Integer value1, Integer value2) {
            addCriterion("killed_q between", value1, value2, "killedQ");
            return (Criteria) this;
        }

        public Criteria andKilledQNotBetween(Integer value1, Integer value2) {
            addCriterion("killed_q not between", value1, value2, "killedQ");
            return (Criteria) this;
        }

        public Criteria andTankKillQIsNull() {
            addCriterion("tank_kill_q is null");
            return (Criteria) this;
        }

        public Criteria andTankKillQIsNotNull() {
            addCriterion("tank_kill_q is not null");
            return (Criteria) this;
        }

        public Criteria andTankKillQEqualTo(Integer value) {
            addCriterion("tank_kill_q =", value, "tankKillQ");
            return (Criteria) this;
        }

        public Criteria andTankKillQNotEqualTo(Integer value) {
            addCriterion("tank_kill_q <>", value, "tankKillQ");
            return (Criteria) this;
        }

        public Criteria andTankKillQGreaterThan(Integer value) {
            addCriterion("tank_kill_q >", value, "tankKillQ");
            return (Criteria) this;
        }

        public Criteria andTankKillQGreaterThanOrEqualTo(Integer value) {
            addCriterion("tank_kill_q >=", value, "tankKillQ");
            return (Criteria) this;
        }

        public Criteria andTankKillQLessThan(Integer value) {
            addCriterion("tank_kill_q <", value, "tankKillQ");
            return (Criteria) this;
        }

        public Criteria andTankKillQLessThanOrEqualTo(Integer value) {
            addCriterion("tank_kill_q <=", value, "tankKillQ");
            return (Criteria) this;
        }

        public Criteria andTankKillQIn(List<Integer> values) {
            addCriterion("tank_kill_q in", values, "tankKillQ");
            return (Criteria) this;
        }

        public Criteria andTankKillQNotIn(List<Integer> values) {
            addCriterion("tank_kill_q not in", values, "tankKillQ");
            return (Criteria) this;
        }

        public Criteria andTankKillQBetween(Integer value1, Integer value2) {
            addCriterion("tank_kill_q between", value1, value2, "tankKillQ");
            return (Criteria) this;
        }

        public Criteria andTankKillQNotBetween(Integer value1, Integer value2) {
            addCriterion("tank_kill_q not between", value1, value2, "tankKillQ");
            return (Criteria) this;
        }

        public Criteria andHeroIsNull() {
            addCriterion("hero is null");
            return (Criteria) this;
        }

        public Criteria andHeroIsNotNull() {
            addCriterion("hero is not null");
            return (Criteria) this;
        }

        public Criteria andHeroEqualTo(String value) {
            addCriterion("hero =", value, "hero");
            return (Criteria) this;
        }

        public Criteria andHeroNotEqualTo(String value) {
            addCriterion("hero <>", value, "hero");
            return (Criteria) this;
        }

        public Criteria andHeroGreaterThan(String value) {
            addCriterion("hero >", value, "hero");
            return (Criteria) this;
        }

        public Criteria andHeroGreaterThanOrEqualTo(String value) {
            addCriterion("hero >=", value, "hero");
            return (Criteria) this;
        }

        public Criteria andHeroLessThan(String value) {
            addCriterion("hero <", value, "hero");
            return (Criteria) this;
        }

        public Criteria andHeroLessThanOrEqualTo(String value) {
            addCriterion("hero <=", value, "hero");
            return (Criteria) this;
        }

        public Criteria andHeroLike(String value) {
            addCriterion("hero like", value, "hero");
            return (Criteria) this;
        }

        public Criteria andHeroNotLike(String value) {
            addCriterion("hero not like", value, "hero");
            return (Criteria) this;
        }

        public Criteria andHeroIn(List<String> values) {
            addCriterion("hero in", values, "hero");
            return (Criteria) this;
        }

        public Criteria andHeroNotIn(List<String> values) {
            addCriterion("hero not in", values, "hero");
            return (Criteria) this;
        }

        public Criteria andHeroBetween(String value1, String value2) {
            addCriterion("hero between", value1, value2, "hero");
            return (Criteria) this;
        }

        public Criteria andHeroNotBetween(String value1, String value2) {
            addCriterion("hero not between", value1, value2, "hero");
            return (Criteria) this;
        }

        public Criteria andDriverIsNull() {
            addCriterion("driver is null");
            return (Criteria) this;
        }

        public Criteria andDriverIsNotNull() {
            addCriterion("driver is not null");
            return (Criteria) this;
        }

        public Criteria andDriverEqualTo(String value) {
            addCriterion("driver =", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverNotEqualTo(String value) {
            addCriterion("driver <>", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverGreaterThan(String value) {
            addCriterion("driver >", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverGreaterThanOrEqualTo(String value) {
            addCriterion("driver >=", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverLessThan(String value) {
            addCriterion("driver <", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverLessThanOrEqualTo(String value) {
            addCriterion("driver <=", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverLike(String value) {
            addCriterion("driver like", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverNotLike(String value) {
            addCriterion("driver not like", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverIn(List<String> values) {
            addCriterion("driver in", values, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverNotIn(List<String> values) {
            addCriterion("driver not in", values, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverBetween(String value1, String value2) {
            addCriterion("driver between", value1, value2, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverNotBetween(String value1, String value2) {
            addCriterion("driver not between", value1, value2, "driver");
            return (Criteria) this;
        }

        public Criteria andMemberNameIsNull() {
            addCriterion("member_name is null");
            return (Criteria) this;
        }

        public Criteria andMemberNameIsNotNull() {
            addCriterion("member_name is not null");
            return (Criteria) this;
        }

        public Criteria andMemberNameEqualTo(String value) {
            addCriterion("member_name =", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotEqualTo(String value) {
            addCriterion("member_name <>", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameGreaterThan(String value) {
            addCriterion("member_name >", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameGreaterThanOrEqualTo(String value) {
            addCriterion("member_name >=", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameLessThan(String value) {
            addCriterion("member_name <", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameLessThanOrEqualTo(String value) {
            addCriterion("member_name <=", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameLike(String value) {
            addCriterion("member_name like", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotLike(String value) {
            addCriterion("member_name not like", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameIn(List<String> values) {
            addCriterion("member_name in", values, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotIn(List<String> values) {
            addCriterion("member_name not in", values, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameBetween(String value1, String value2) {
            addCriterion("member_name between", value1, value2, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotBetween(String value1, String value2) {
            addCriterion("member_name not between", value1, value2, "memberName");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("level like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("level not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity_data
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 18 22:46:19 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}