package org.brjia.qs.model;

import java.util.Date;

public class GangRegDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gang_reg.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gang_reg.name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gang_reg.level
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gang_reg.gang_real_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String gangRealId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gang_reg.area_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gang_reg.create_time
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gang_reg.id
     *
     * @return the value of gang_reg.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gang_reg.id
     *
     * @param id the value for gang_reg.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gang_reg.name
     *
     * @return the value of gang_reg.name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gang_reg.name
     *
     * @param name the value for gang_reg.name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gang_reg.level
     *
     * @return the value of gang_reg.level
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gang_reg.level
     *
     * @param level the value for gang_reg.level
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gang_reg.gang_real_id
     *
     * @return the value of gang_reg.gang_real_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getGangRealId() {
        return gangRealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gang_reg.gang_real_id
     *
     * @param gangRealId the value for gang_reg.gang_real_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setGangRealId(String gangRealId) {
        this.gangRealId = gangRealId == null ? null : gangRealId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gang_reg.area_id
     *
     * @return the value of gang_reg.area_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gang_reg.area_id
     *
     * @param areaId the value for gang_reg.area_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gang_reg.create_time
     *
     * @return the value of gang_reg.create_time
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gang_reg.create_time
     *
     * @param createTime the value for gang_reg.create_time
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}