package org.brjia.qs.model;

import java.util.Date;

public class MemberRegDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_reg.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_reg.name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_reg.level
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_reg.role
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_reg.gang_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer gangId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_reg.member_real_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String memberRealId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_reg.family_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer familyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_reg.area_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_reg.create_time
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_reg.id
     *
     * @return the value of member_reg.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_reg.id
     *
     * @param id the value for member_reg.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_reg.name
     *
     * @return the value of member_reg.name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_reg.name
     *
     * @param name the value for member_reg.name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_reg.level
     *
     * @return the value of member_reg.level
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_reg.level
     *
     * @param level the value for member_reg.level
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_reg.role
     *
     * @return the value of member_reg.role
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_reg.role
     *
     * @param role the value for member_reg.role
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_reg.gang_id
     *
     * @return the value of member_reg.gang_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getGangId() {
        return gangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_reg.gang_id
     *
     * @param gangId the value for member_reg.gang_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setGangId(Integer gangId) {
        this.gangId = gangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_reg.member_real_id
     *
     * @return the value of member_reg.member_real_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getMemberRealId() {
        return memberRealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_reg.member_real_id
     *
     * @param memberRealId the value for member_reg.member_real_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setMemberRealId(String memberRealId) {
        this.memberRealId = memberRealId == null ? null : memberRealId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_reg.family_id
     *
     * @return the value of member_reg.family_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getFamilyId() {
        return familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_reg.family_id
     *
     * @param familyId the value for member_reg.family_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setFamilyId(Integer familyId) {
        this.familyId = familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_reg.area_id
     *
     * @return the value of member_reg.area_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_reg.area_id
     *
     * @param areaId the value for member_reg.area_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_reg.create_time
     *
     * @return the value of member_reg.create_time
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_reg.create_time
     *
     * @param createTime the value for member_reg.create_time
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}