package org.brjia.qs.model;

import java.util.Date;

public class SummaryDataRegDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.year
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.week
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.round
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer round;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.area_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.gang_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer gangId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.upload_date
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Date uploadDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.kill_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer killQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.assist_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer assistQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.carry_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer carryQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.output_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer outputM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.cure_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer cureM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.bear_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer bearM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.corpse_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer corpseQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.relive_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer reliveQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.killed_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer killedQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.tank_kill_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer tankKillQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.hero
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer hero;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.driver
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer driver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.gang_name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String gangName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.enemy_summary_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer enemySummaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.duration
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.count
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_summary.dead_count
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer deadCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.id
     *
     * @return the value of activity_summary.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.id
     *
     * @param id the value for activity_summary.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.year
     *
     * @return the value of activity_summary.year
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.year
     *
     * @param year the value for activity_summary.year
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.week
     *
     * @return the value of activity_summary.week
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.week
     *
     * @param week the value for activity_summary.week
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setWeek(Integer week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.round
     *
     * @return the value of activity_summary.round
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getRound() {
        return round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.round
     *
     * @param round the value for activity_summary.round
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setRound(Integer round) {
        this.round = round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.area_id
     *
     * @return the value of activity_summary.area_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.area_id
     *
     * @param areaId the value for activity_summary.area_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.gang_id
     *
     * @return the value of activity_summary.gang_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getGangId() {
        return gangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.gang_id
     *
     * @param gangId the value for activity_summary.gang_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setGangId(Integer gangId) {
        this.gangId = gangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.upload_date
     *
     * @return the value of activity_summary.upload_date
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.upload_date
     *
     * @param uploadDate the value for activity_summary.upload_date
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.kill_q
     *
     * @return the value of activity_summary.kill_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getKillQ() {
        return killQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.kill_q
     *
     * @param killQ the value for activity_summary.kill_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setKillQ(Integer killQ) {
        this.killQ = killQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.assist_q
     *
     * @return the value of activity_summary.assist_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getAssistQ() {
        return assistQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.assist_q
     *
     * @param assistQ the value for activity_summary.assist_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setAssistQ(Integer assistQ) {
        this.assistQ = assistQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.carry_q
     *
     * @return the value of activity_summary.carry_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getCarryQ() {
        return carryQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.carry_q
     *
     * @param carryQ the value for activity_summary.carry_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setCarryQ(Integer carryQ) {
        this.carryQ = carryQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.output_m
     *
     * @return the value of activity_summary.output_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getOutputM() {
        return outputM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.output_m
     *
     * @param outputM the value for activity_summary.output_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setOutputM(Integer outputM) {
        this.outputM = outputM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.cure_m
     *
     * @return the value of activity_summary.cure_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getCureM() {
        return cureM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.cure_m
     *
     * @param cureM the value for activity_summary.cure_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setCureM(Integer cureM) {
        this.cureM = cureM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.bear_m
     *
     * @return the value of activity_summary.bear_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getBearM() {
        return bearM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.bear_m
     *
     * @param bearM the value for activity_summary.bear_m
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setBearM(Integer bearM) {
        this.bearM = bearM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.corpse_q
     *
     * @return the value of activity_summary.corpse_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getCorpseQ() {
        return corpseQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.corpse_q
     *
     * @param corpseQ the value for activity_summary.corpse_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setCorpseQ(Integer corpseQ) {
        this.corpseQ = corpseQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.relive_q
     *
     * @return the value of activity_summary.relive_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getReliveQ() {
        return reliveQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.relive_q
     *
     * @param reliveQ the value for activity_summary.relive_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setReliveQ(Integer reliveQ) {
        this.reliveQ = reliveQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.killed_q
     *
     * @return the value of activity_summary.killed_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getKilledQ() {
        return killedQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.killed_q
     *
     * @param killedQ the value for activity_summary.killed_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setKilledQ(Integer killedQ) {
        this.killedQ = killedQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.tank_kill_q
     *
     * @return the value of activity_summary.tank_kill_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getTankKillQ() {
        return tankKillQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.tank_kill_q
     *
     * @param tankKillQ the value for activity_summary.tank_kill_q
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setTankKillQ(Integer tankKillQ) {
        this.tankKillQ = tankKillQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.hero
     *
     * @return the value of activity_summary.hero
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getHero() {
        return hero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.hero
     *
     * @param hero the value for activity_summary.hero
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setHero(Integer hero) {
        this.hero = hero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.driver
     *
     * @return the value of activity_summary.driver
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getDriver() {
        return driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.driver
     *
     * @param driver the value for activity_summary.driver
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setDriver(Integer driver) {
        this.driver = driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.gang_name
     *
     * @return the value of activity_summary.gang_name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getGangName() {
        return gangName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.gang_name
     *
     * @param gangName the value for activity_summary.gang_name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setGangName(String gangName) {
        this.gangName = gangName == null ? null : gangName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.enemy_summary_id
     *
     * @return the value of activity_summary.enemy_summary_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getEnemySummaryId() {
        return enemySummaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.enemy_summary_id
     *
     * @param enemySummaryId the value for activity_summary.enemy_summary_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setEnemySummaryId(Integer enemySummaryId) {
        this.enemySummaryId = enemySummaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.duration
     *
     * @return the value of activity_summary.duration
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.duration
     *
     * @param duration the value for activity_summary.duration
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.count
     *
     * @return the value of activity_summary.count
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.count
     *
     * @param count the value for activity_summary.count
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_summary.dead_count
     *
     * @return the value of activity_summary.dead_count
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getDeadCount() {
        return deadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_summary.dead_count
     *
     * @param deadCount the value for activity_summary.dead_count
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setDeadCount(Integer deadCount) {
        this.deadCount = deadCount;
    }
}