package org.brjia.qs.model;

import java.util.Date;

public class UploadStateRegDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_state_reg.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_state_reg.create_user
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_state_reg.create_time
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_state_reg.year
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_state_reg.week
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_state_reg.round
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer round;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_state_reg.gang_name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String gangName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_state_reg.areaId
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_state_reg.signature
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_state_reg.summary_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    private Integer summaryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_state_reg.id
     *
     * @return the value of upload_state_reg.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_state_reg.id
     *
     * @param id the value for upload_state_reg.id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_state_reg.create_user
     *
     * @return the value of upload_state_reg.create_user
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_state_reg.create_user
     *
     * @param createUser the value for upload_state_reg.create_user
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_state_reg.create_time
     *
     * @return the value of upload_state_reg.create_time
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_state_reg.create_time
     *
     * @param createTime the value for upload_state_reg.create_time
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_state_reg.year
     *
     * @return the value of upload_state_reg.year
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_state_reg.year
     *
     * @param year the value for upload_state_reg.year
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_state_reg.week
     *
     * @return the value of upload_state_reg.week
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_state_reg.week
     *
     * @param week the value for upload_state_reg.week
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setWeek(Integer week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_state_reg.round
     *
     * @return the value of upload_state_reg.round
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getRound() {
        return round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_state_reg.round
     *
     * @param round the value for upload_state_reg.round
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setRound(Integer round) {
        this.round = round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_state_reg.gang_name
     *
     * @return the value of upload_state_reg.gang_name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getGangName() {
        return gangName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_state_reg.gang_name
     *
     * @param gangName the value for upload_state_reg.gang_name
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setGangName(String gangName) {
        this.gangName = gangName == null ? null : gangName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_state_reg.areaId
     *
     * @return the value of upload_state_reg.areaId
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_state_reg.areaId
     *
     * @param areaid the value for upload_state_reg.areaId
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_state_reg.signature
     *
     * @return the value of upload_state_reg.signature
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_state_reg.signature
     *
     * @param signature the value for upload_state_reg.signature
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_state_reg.summary_id
     *
     * @return the value of upload_state_reg.summary_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public Integer getSummaryId() {
        return summaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_state_reg.summary_id
     *
     * @param summaryId the value for upload_state_reg.summary_id
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    public void setSummaryId(Integer summaryId) {
        this.summaryId = summaryId;
    }
}