package org.brjia.qs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.brjia.qs.model.AreaRegDTO;
import org.brjia.qs.model.AreaRegDTOExample;

public interface AreaRegDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int countByExample(AreaRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int deleteByExample(AreaRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int insert(AreaRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int insertSelective(AreaRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    List<AreaRegDTO> selectByExample(AreaRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    AreaRegDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") AreaRegDTO record, @Param("example") AreaRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByExample(@Param("record") AreaRegDTO record, @Param("example") AreaRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByPrimaryKeySelective(AreaRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByPrimaryKey(AreaRegDTO record);
}