package org.brjia.qs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.brjia.qs.model.FamilyRegDTO;
import org.brjia.qs.model.FamilyRegDTOExample;

public interface FamilyRegDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int countByExample(FamilyRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int deleteByExample(FamilyRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int insert(FamilyRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int insertSelective(FamilyRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    List<FamilyRegDTO> selectByExample(FamilyRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    FamilyRegDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") FamilyRegDTO record, @Param("example") FamilyRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByExample(@Param("record") FamilyRegDTO record, @Param("example") FamilyRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByPrimaryKeySelective(FamilyRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByPrimaryKey(FamilyRegDTO record);
}