package org.brjia.qs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.brjia.qs.model.FightingListDataRegDTO;
import org.brjia.qs.model.FightingListDataRegDTOExample;

public interface FightingListDataRegDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int countByExample(FightingListDataRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int deleteByExample(FightingListDataRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int insert(FightingListDataRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int insertSelective(FightingListDataRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    List<FightingListDataRegDTO> selectByExample(FightingListDataRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    FightingListDataRegDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") FightingListDataRegDTO record, @Param("example") FightingListDataRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByExample(@Param("record") FightingListDataRegDTO record, @Param("example") FightingListDataRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByPrimaryKeySelective(FightingListDataRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByPrimaryKey(FightingListDataRegDTO record);
}