package org.brjia.qs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.brjia.qs.model.GangRegDTO;
import org.brjia.qs.model.GangRegDTOExample;

public interface GangRegDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int countByExample(GangRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int deleteByExample(GangRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int insert(GangRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int insertSelective(GangRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    List<GangRegDTO> selectByExample(GangRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    GangRegDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") GangRegDTO record, @Param("example") GangRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByExample(@Param("record") GangRegDTO record, @Param("example") GangRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByPrimaryKeySelective(GangRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gang_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByPrimaryKey(GangRegDTO record);
}