package org.brjia.qs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.brjia.qs.model.MemberRegDTO;
import org.brjia.qs.model.MemberRegDTOExample;

public interface MemberRegDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int countByExample(MemberRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int deleteByExample(MemberRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int insert(MemberRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int insertSelective(MemberRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    List<MemberRegDTO> selectByExample(MemberRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    MemberRegDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") MemberRegDTO record, @Param("example") MemberRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByExample(@Param("record") MemberRegDTO record, @Param("example") MemberRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByPrimaryKeySelective(MemberRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByPrimaryKey(MemberRegDTO record);
}