package org.brjia.qs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.brjia.qs.model.SummaryDataRegDTO;
import org.brjia.qs.model.SummaryDataRegDTOExample;

public interface SummaryDataRegDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_summary
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int countByExample(SummaryDataRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_summary
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int deleteByExample(SummaryDataRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_summary
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_summary
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int insert(SummaryDataRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_summary
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int insertSelective(SummaryDataRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_summary
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    List<SummaryDataRegDTO> selectByExample(SummaryDataRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_summary
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    SummaryDataRegDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_summary
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") SummaryDataRegDTO record, @Param("example") SummaryDataRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_summary
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByExample(@Param("record") SummaryDataRegDTO record, @Param("example") SummaryDataRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_summary
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByPrimaryKeySelective(SummaryDataRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_summary
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByPrimaryKey(SummaryDataRegDTO record);
}