package org.brjia.qs.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.brjia.qs.model.UploadStateRegDTO;
import org.brjia.qs.model.UploadStateRegDTOExample;

public interface UploadStateRegDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_state_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int countByExample(UploadStateRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_state_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int deleteByExample(UploadStateRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_state_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_state_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int insert(UploadStateRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_state_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int insertSelective(UploadStateRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_state_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    List<UploadStateRegDTO> selectByExample(UploadStateRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_state_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    UploadStateRegDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_state_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") UploadStateRegDTO record, @Param("example") UploadStateRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_state_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByExample(@Param("record") UploadStateRegDTO record, @Param("example") UploadStateRegDTOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_state_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByPrimaryKeySelective(UploadStateRegDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_state_reg
     *
     * @mbggenerated Mon Apr 18 22:46:19 CST 2016
     */
    int updateByPrimaryKey(UploadStateRegDTO record);
}